spring.application.name=OnlineShop

spring.datasource.url=jdbc:postgresql://localhost:5433/onlineshop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MyVerySecretKeyForJwtAuthenticationOnlineShopProject123456
jwt.expiration=86400000